version: '2'
services:
 proxy:
  container_name: proxy
  build: ./
  image: nginx-proxy
  networks:
    - website1
    - website2
  ports:
   - 80:80
   - 443:443
  volumes: 
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./backend-not-found.html:/var/www/html/backend-not-found.html
    - ./includes/:/etc/nginx/includes/
    - ./ssl/:/etc/ssl/certs/nginx/

networks:
  website1:
    external:
      name: website1_default
  website2:
    external:
      name: website2_default

# networks:
#   aws-webserver-network:
#     external: 
#       name: aws-webserver-network